name: 'Notion database properties validator'
description: 'Validates Notion Database properties against user-defined specifications'
author: 'ajchemist'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'command'
  color: 'red'

# Define your inputs here.
inputs:
  notion_token:
    description: 'Notion API Token'
    required: true
  database_id:
    description: 'Notion Database ID'
    required: true
  database_spec:
    description: 'JSON string specifying the expected database configuration'
    required: true    


# Define your outputs here.
outputs:
  validation_success:
    description: 'Boolean indicating whether the validation was successful'
  failure_reason:
    description: 'Description of why the validation failed, if it did'

runs:
  using: node20
  main: dist/index.js
